#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  Sonar,          sensorSONAR_cm)
#pragma config(Motor,  port2,           LeftMotor,     tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Sensor, in6,    potentiometer,  sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
//***********************************************************************************//
//                                                                                   //
// This is the first program to be experimented with the recbot                      //
// It first waits for the start signal: pushing joystick 6U botton                   //
// After receiving the start signal, it moves forward 2 yards, make a 90 degree      //
// sharp left turn, move forward 2 yards, makes a 90 degree sharp righ turn          //
// move forward 2 yards and stop there                                               //
//                                                                                   //
// The program uses the following sub functions                                      //
//                                                                                   //
//  MakeTurn90( int direc)                                                           //
//  -- If direc = 1, the robot makes a 90 degree left turn                           //
//  -- If direc = 0, the robot makes a 90 degree right turn                          //
//                                                                                   //
//  MakeTurn180( )                                                                   //
//  -- the robot makes a 90 degree turn                                              //
//                                                                                   //
//  Move( int direc, int dist )                                                      //
//  -- If direc =1, the robot moves forward for dist feet                            //
//  -- If direc =0, the robot moves backward for dist feet                           //
//                                                                                   //
//  Last modified on 5/23/2017                                                       //
//                                                                                   //
//***********************************************************************************//

void Move(int direc, int dist)
{
	int N, M;
	N = 360*dist*12/(3.1415926*2.75);
	M = -N;
	SensorValue[RightEncoder]=0;                    // reset the shaft encoders

	if (direc==1) {                                 // move forward
		motor[LeftMotor] = 63;                        // assign positive motor speed
		motor[RightMotor] = 63;
		while (SensorValue[RightEncoder]<N) {}        // let motor run till the encoder reaches its target value
	  motor[LeftMotor] = 0;                         // stop the motors
		motor[RightMotor] = 0;
	}
	else {                                          // move backward
	  motor[LeftMotor] = -63;                       // assign negative motor speed
		motor[RightMotor] = -63;
		while (SensorValue[RightEncoder]>M)           // let motor run till the encoder reaches its target value
	  motor[LeftMotor] = 0;                         // stop the motors
		motor[RightMotor] = 0;
   }
		wait(1);                                      // wait 1 second to let the robot fully stop
 }


void MakeTurn90(int direc)
{
	SensorValue[RightEncoder]=0;                    // reset the shaft encoders


	if (direc==1) {                                 // left turn
		motor[LeftMotor] = -63;                       // left motor backward
		motor[RightMotor] = 63;                       // right motor forward
		while (SensorValue[RightEncoder]<499) {}        // let motor run till the encoder reaches its target value
	  motor[LeftMotor] = 0;                         // stop the motors
		motor[RightMotor] = 0;
	}
	else {                                          // right turn
	  motor[LeftMotor] = 63;                        // left motor forward
		motor[RightMotor] = -63;                      // right motor backward
		while (SensorValue[RightEncoder]>-499) {}     // let motor run till the encoder reaches its target value
	  motor[LeftMotor] = 0;                         // stop the motors
		motor[RightMotor] = 0;
   }
		wait(1);                                      // wait 1 second to let the robot fully stop
 }

void MakeTurn180( )
{
		SensorValue[RightEncoder]=0;                  // reset the shaft encoders


		motor[LeftMotor] = -63;                       // left motor backward
		motor[RightMotor] = 63;                       // right motor forward
		while (SensorValue[RightEncoder]<1008) {}        // let motor run till the encoder reaches its target value
	  motor[LeftMotor] = 0;                         // stop the motors
		motor[RightMotor] = 0;

		wait(1);                                      // wait 1 second to let the robot fully stop
}

task main()
{

	int run;
  run = 0;

	while (true) {                                  // make the microconrolled repeatly doing the following tasks
	  while (run==0) {                              //
			run = vexRT[Btn6U];                         // continuously check if button 6U is pushed
		}
	  run = 0;                                      // reset run for the next round operation

	  Move(1, 2);                                   // move forward for 2 yards
	  MakeTurn90(1);                                // make a left turn
	  Move(1, 2);                                   // move forward for 2 yards
	  MakeTurn90(0);                                // make a right turn
	  Move(1, 2);                                   // move forward for 2 yards

	  MakeTurn180();                                // make a 180 degree turn
	  // the robot reaches its destination by now
	  // Put your code below to make the robot traveling back



	  // Put your code above this line
 }
}
